version: '3.8'

services:
  store:
    image: mcr.microsoft.com/mssql/server
    environment:
      MSSQL_SA_PASSWORD: 'gifttech!3201'
      ACCEPT_EULA: Y
      MSSQL_PID: Express
      MSSQL_TCP_PORT: 2000
    ports:
      - "2000:2000"
