version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Gifttech@3201"   # Đặt mật khẩu mạnh cho tài khoản SA
      ACCEPT_EULA: Y
    ports:
      - "27021:1433"   # Map cổng máy host với cổng của container

  init-database:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sql-server
    environment:
      SA_PASSWORD: "Gifttech@3201"   
      ACCEPT_EULA: Y
    command: /bin/bash -c 'sleep 30s && /opt/mssql-tools/bin/sqlcmd -S sql-server -U SA -P Gifttech@3201 -d master -i /scripts/init-db.sql'
    volumes:
      - ./init-db.sql:/scripts/init-db.sql   # Đường dẫn đến script SQL tạo cơ sở dữ liệu

